baseURL: https://laxelebon.netlify.app
languageCode: en-us
summaryLength: '10'
theme: kross-hugo
title: ZONGO
params:
  address: koudougou, secteur 5 
  author: ZONGO JOACHIM AXEL
  contact:
    enable: yes
    form_action: 'axelzongo06@gmail.com'
  cookies:
    enable: yes
    expire_days: 2
  copyright: Copyright ; 2021 a theme by zongo j axel
  description: This is meta description
  email: axelzongo06@gmail.com
  google_analytics_id: ''
  home: Home
  logo: ''
  map:
    enable: no
    gmap_api: https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en
    map_latitude: '51.5223477'
    map_longitude: '-0.1622023'
    map_marker: images/marker.png
  phone: +226 73424805
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/slick/slick.css
      - link: plugins/themify-icons/themify-icons.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/google-map/map.js
  preloader:
    enable: yes
    preloader: images/preloader.gif
  social:
    - URL: 'https://web.facebook.com/profile.php?id=100009767682212'
      icon: ti-facebook
    - URL: 'https://www.instagram.com/zongoaxel/'
      icon: ti-instagram
    #- URL: '#'
     # icon: ti-dribbble
    #- URL: '#'
     # icon: ti-twitter-alt
  theme_color: '#41228e'
menu:
  main:
    - URL: about
      name: About
      weight: 1
    #- URL: blog
     # name: Blog
      #weight: 2
    - URL: contact
      name: Contact
      weight: 4
